/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppTutoresRouteImport } from './routes/_authenticated/app.tutores'
import { Route as AuthenticatedAppTarefasRouteImport } from './routes/_authenticated/app.tarefas'
import { Route as AuthenticatedAppSaudeRouteImport } from './routes/_authenticated/app.saude'
import { Route as AuthenticatedAppRelatoriosRouteImport } from './routes/_authenticated/app.relatorios'
import { Route as AuthenticatedAppProgramacaoRouteImport } from './routes/_authenticated/app.programacao'
import { Route as AuthenticatedAppOcorrenciasRouteImport } from './routes/_authenticated/app.ocorrencias'
import { Route as AuthenticatedAppHospedagemRouteImport } from './routes/_authenticated/app.hospedagem'
import { Route as AuthenticatedAppFinanceiroRouteImport } from './routes/_authenticated/app.financeiro'
import { Route as AuthenticatedAppDocumentosRouteImport } from './routes/_authenticated/app.documentos'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated/app.configuracoes'
import { Route as AuthenticatedAppCaesRouteImport } from './routes/_authenticated/app.caes'
import { Route as AuthenticatedAppBoletinsRouteImport } from './routes/_authenticated/app.boletins'
import { Route as AuthenticatedAppBanhoTosaRouteImport } from './routes/_authenticated/app.banho-tosa'
import { Route as AuthenticatedAppAgendaRouteImport } from './routes/_authenticated/app.agenda'
import { Route as AuthenticatedAppHospedagemIdRelatorioRouteImport } from './routes/_authenticated/app.hospedagem.$id.relatorio'
import { Route as AuthenticatedAppCaesIdTimelineRouteImport } from './routes/_authenticated/app.caes.$id.timeline'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTutoresRoute = AuthenticatedAppTutoresRouteImport.update({
  id: '/tutores',
  path: '/tutores',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTarefasRoute = AuthenticatedAppTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSaudeRoute = AuthenticatedAppSaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRelatoriosRoute =
  AuthenticatedAppRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProgramacaoRoute =
  AuthenticatedAppProgramacaoRouteImport.update({
    id: '/programacao',
    path: '/programacao',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOcorrenciasRoute =
  AuthenticatedAppOcorrenciasRouteImport.update({
    id: '/ocorrencias',
    path: '/ocorrencias',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHospedagemRoute =
  AuthenticatedAppHospedagemRouteImport.update({
    id: '/hospedagem',
    path: '/hospedagem',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFinanceiroRoute =
  AuthenticatedAppFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDocumentosRoute =
  AuthenticatedAppDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCaesRoute = AuthenticatedAppCaesRouteImport.update({
  id: '/caes',
  path: '/caes',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBoletinsRoute =
  AuthenticatedAppBoletinsRouteImport.update({
    id: '/boletins',
    path: '/boletins',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBanhoTosaRoute =
  AuthenticatedAppBanhoTosaRouteImport.update({
    id: '/banho-tosa',
    path: '/banho-tosa',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAgendaRoute = AuthenticatedAppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppHospedagemIdRelatorioRoute =
  AuthenticatedAppHospedagemIdRelatorioRouteImport.update({
    id: '/$id/relatorio',
    path: '/$id/relatorio',
    getParentRoute: () => AuthenticatedAppHospedagemRoute,
  } as any)
const AuthenticatedAppCaesIdTimelineRoute =
  AuthenticatedAppCaesIdTimelineRouteImport.update({
    id: '/$id/timeline',
    path: '/$id/timeline',
    getParentRoute: () => AuthenticatedAppCaesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/banho-tosa': typeof AuthenticatedAppBanhoTosaRoute
  '/app/boletins': typeof AuthenticatedAppBoletinsRoute
  '/app/caes': typeof AuthenticatedAppCaesRouteWithChildren
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/app/hospedagem': typeof AuthenticatedAppHospedagemRouteWithChildren
  '/app/ocorrencias': typeof AuthenticatedAppOcorrenciasRoute
  '/app/programacao': typeof AuthenticatedAppProgramacaoRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app/saude': typeof AuthenticatedAppSaudeRoute
  '/app/tarefas': typeof AuthenticatedAppTarefasRoute
  '/app/tutores': typeof AuthenticatedAppTutoresRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/caes/$id/timeline': typeof AuthenticatedAppCaesIdTimelineRoute
  '/app/hospedagem/$id/relatorio': typeof AuthenticatedAppHospedagemIdRelatorioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/banho-tosa': typeof AuthenticatedAppBanhoTosaRoute
  '/app/boletins': typeof AuthenticatedAppBoletinsRoute
  '/app/caes': typeof AuthenticatedAppCaesRouteWithChildren
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/app/hospedagem': typeof AuthenticatedAppHospedagemRouteWithChildren
  '/app/ocorrencias': typeof AuthenticatedAppOcorrenciasRoute
  '/app/programacao': typeof AuthenticatedAppProgramacaoRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app/saude': typeof AuthenticatedAppSaudeRoute
  '/app/tarefas': typeof AuthenticatedAppTarefasRoute
  '/app/tutores': typeof AuthenticatedAppTutoresRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/caes/$id/timeline': typeof AuthenticatedAppCaesIdTimelineRoute
  '/app/hospedagem/$id/relatorio': typeof AuthenticatedAppHospedagemIdRelatorioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/_authenticated/app/banho-tosa': typeof AuthenticatedAppBanhoTosaRoute
  '/_authenticated/app/boletins': typeof AuthenticatedAppBoletinsRoute
  '/_authenticated/app/caes': typeof AuthenticatedAppCaesRouteWithChildren
  '/_authenticated/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/_authenticated/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/_authenticated/app/hospedagem': typeof AuthenticatedAppHospedagemRouteWithChildren
  '/_authenticated/app/ocorrencias': typeof AuthenticatedAppOcorrenciasRoute
  '/_authenticated/app/programacao': typeof AuthenticatedAppProgramacaoRoute
  '/_authenticated/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/_authenticated/app/saude': typeof AuthenticatedAppSaudeRoute
  '/_authenticated/app/tarefas': typeof AuthenticatedAppTarefasRoute
  '/_authenticated/app/tutores': typeof AuthenticatedAppTutoresRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/caes/$id/timeline': typeof AuthenticatedAppCaesIdTimelineRoute
  '/_authenticated/app/hospedagem/$id/relatorio': typeof AuthenticatedAppHospedagemIdRelatorioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app'
    | '/app/agenda'
    | '/app/banho-tosa'
    | '/app/boletins'
    | '/app/caes'
    | '/app/configuracoes'
    | '/app/documentos'
    | '/app/financeiro'
    | '/app/hospedagem'
    | '/app/ocorrencias'
    | '/app/programacao'
    | '/app/relatorios'
    | '/app/saude'
    | '/app/tarefas'
    | '/app/tutores'
    | '/app/'
    | '/app/caes/$id/timeline'
    | '/app/hospedagem/$id/relatorio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app/agenda'
    | '/app/banho-tosa'
    | '/app/boletins'
    | '/app/caes'
    | '/app/configuracoes'
    | '/app/documentos'
    | '/app/financeiro'
    | '/app/hospedagem'
    | '/app/ocorrencias'
    | '/app/programacao'
    | '/app/relatorios'
    | '/app/saude'
    | '/app/tarefas'
    | '/app/tutores'
    | '/app'
    | '/app/caes/$id/timeline'
    | '/app/hospedagem/$id/relatorio'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/app/agenda'
    | '/_authenticated/app/banho-tosa'
    | '/_authenticated/app/boletins'
    | '/_authenticated/app/caes'
    | '/_authenticated/app/configuracoes'
    | '/_authenticated/app/documentos'
    | '/_authenticated/app/financeiro'
    | '/_authenticated/app/hospedagem'
    | '/_authenticated/app/ocorrencias'
    | '/_authenticated/app/programacao'
    | '/_authenticated/app/relatorios'
    | '/_authenticated/app/saude'
    | '/_authenticated/app/tarefas'
    | '/_authenticated/app/tutores'
    | '/_authenticated/app/'
    | '/_authenticated/app/caes/$id/timeline'
    | '/_authenticated/app/hospedagem/$id/relatorio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tutores': {
      id: '/_authenticated/app/tutores'
      path: '/tutores'
      fullPath: '/app/tutores'
      preLoaderRoute: typeof AuthenticatedAppTutoresRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tarefas': {
      id: '/_authenticated/app/tarefas'
      path: '/tarefas'
      fullPath: '/app/tarefas'
      preLoaderRoute: typeof AuthenticatedAppTarefasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/saude': {
      id: '/_authenticated/app/saude'
      path: '/saude'
      fullPath: '/app/saude'
      preLoaderRoute: typeof AuthenticatedAppSaudeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/relatorios': {
      id: '/_authenticated/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AuthenticatedAppRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/programacao': {
      id: '/_authenticated/app/programacao'
      path: '/programacao'
      fullPath: '/app/programacao'
      preLoaderRoute: typeof AuthenticatedAppProgramacaoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ocorrencias': {
      id: '/_authenticated/app/ocorrencias'
      path: '/ocorrencias'
      fullPath: '/app/ocorrencias'
      preLoaderRoute: typeof AuthenticatedAppOcorrenciasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/hospedagem': {
      id: '/_authenticated/app/hospedagem'
      path: '/hospedagem'
      fullPath: '/app/hospedagem'
      preLoaderRoute: typeof AuthenticatedAppHospedagemRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/financeiro': {
      id: '/_authenticated/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/documentos': {
      id: '/_authenticated/app/documentos'
      path: '/documentos'
      fullPath: '/app/documentos'
      preLoaderRoute: typeof AuthenticatedAppDocumentosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/configuracoes': {
      id: '/_authenticated/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/caes': {
      id: '/_authenticated/app/caes'
      path: '/caes'
      fullPath: '/app/caes'
      preLoaderRoute: typeof AuthenticatedAppCaesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/boletins': {
      id: '/_authenticated/app/boletins'
      path: '/boletins'
      fullPath: '/app/boletins'
      preLoaderRoute: typeof AuthenticatedAppBoletinsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/banho-tosa': {
      id: '/_authenticated/app/banho-tosa'
      path: '/banho-tosa'
      fullPath: '/app/banho-tosa'
      preLoaderRoute: typeof AuthenticatedAppBanhoTosaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agenda': {
      id: '/_authenticated/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AuthenticatedAppAgendaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/hospedagem/$id/relatorio': {
      id: '/_authenticated/app/hospedagem/$id/relatorio'
      path: '/$id/relatorio'
      fullPath: '/app/hospedagem/$id/relatorio'
      preLoaderRoute: typeof AuthenticatedAppHospedagemIdRelatorioRouteImport
      parentRoute: typeof AuthenticatedAppHospedagemRoute
    }
    '/_authenticated/app/caes/$id/timeline': {
      id: '/_authenticated/app/caes/$id/timeline'
      path: '/$id/timeline'
      fullPath: '/app/caes/$id/timeline'
      preLoaderRoute: typeof AuthenticatedAppCaesIdTimelineRouteImport
      parentRoute: typeof AuthenticatedAppCaesRoute
    }
  }
}

interface AuthenticatedAppCaesRouteChildren {
  AuthenticatedAppCaesIdTimelineRoute: typeof AuthenticatedAppCaesIdTimelineRoute
}

const AuthenticatedAppCaesRouteChildren: AuthenticatedAppCaesRouteChildren = {
  AuthenticatedAppCaesIdTimelineRoute: AuthenticatedAppCaesIdTimelineRoute,
}

const AuthenticatedAppCaesRouteWithChildren =
  AuthenticatedAppCaesRoute._addFileChildren(AuthenticatedAppCaesRouteChildren)

interface AuthenticatedAppHospedagemRouteChildren {
  AuthenticatedAppHospedagemIdRelatorioRoute: typeof AuthenticatedAppHospedagemIdRelatorioRoute
}

const AuthenticatedAppHospedagemRouteChildren: AuthenticatedAppHospedagemRouteChildren =
  {
    AuthenticatedAppHospedagemIdRelatorioRoute:
      AuthenticatedAppHospedagemIdRelatorioRoute,
  }

const AuthenticatedAppHospedagemRouteWithChildren =
  AuthenticatedAppHospedagemRoute._addFileChildren(
    AuthenticatedAppHospedagemRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAgendaRoute: typeof AuthenticatedAppAgendaRoute
  AuthenticatedAppBanhoTosaRoute: typeof AuthenticatedAppBanhoTosaRoute
  AuthenticatedAppBoletinsRoute: typeof AuthenticatedAppBoletinsRoute
  AuthenticatedAppCaesRoute: typeof AuthenticatedAppCaesRouteWithChildren
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppDocumentosRoute: typeof AuthenticatedAppDocumentosRoute
  AuthenticatedAppFinanceiroRoute: typeof AuthenticatedAppFinanceiroRoute
  AuthenticatedAppHospedagemRoute: typeof AuthenticatedAppHospedagemRouteWithChildren
  AuthenticatedAppOcorrenciasRoute: typeof AuthenticatedAppOcorrenciasRoute
  AuthenticatedAppProgramacaoRoute: typeof AuthenticatedAppProgramacaoRoute
  AuthenticatedAppRelatoriosRoute: typeof AuthenticatedAppRelatoriosRoute
  AuthenticatedAppSaudeRoute: typeof AuthenticatedAppSaudeRoute
  AuthenticatedAppTarefasRoute: typeof AuthenticatedAppTarefasRoute
  AuthenticatedAppTutoresRoute: typeof AuthenticatedAppTutoresRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAgendaRoute: AuthenticatedAppAgendaRoute,
  AuthenticatedAppBanhoTosaRoute: AuthenticatedAppBanhoTosaRoute,
  AuthenticatedAppBoletinsRoute: AuthenticatedAppBoletinsRoute,
  AuthenticatedAppCaesRoute: AuthenticatedAppCaesRouteWithChildren,
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppDocumentosRoute: AuthenticatedAppDocumentosRoute,
  AuthenticatedAppFinanceiroRoute: AuthenticatedAppFinanceiroRoute,
  AuthenticatedAppHospedagemRoute: AuthenticatedAppHospedagemRouteWithChildren,
  AuthenticatedAppOcorrenciasRoute: AuthenticatedAppOcorrenciasRoute,
  AuthenticatedAppProgramacaoRoute: AuthenticatedAppProgramacaoRoute,
  AuthenticatedAppRelatoriosRoute: AuthenticatedAppRelatoriosRoute,
  AuthenticatedAppSaudeRoute: AuthenticatedAppSaudeRoute,
  AuthenticatedAppTarefasRoute: AuthenticatedAppTarefasRoute,
  AuthenticatedAppTutoresRoute: AuthenticatedAppTutoresRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
