/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTutorRouteImport } from './routes/_authenticated/tutor'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedTutorIndexRouteImport } from './routes/_authenticated/tutor.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedTutorStoriesRouteImport } from './routes/_authenticated/tutor.stories'
import { Route as AuthenticatedTutorFinanceiroRouteImport } from './routes/_authenticated/tutor.financeiro'
import { Route as AuthenticatedTutorDocumentosRouteImport } from './routes/_authenticated/tutor.documentos'
import { Route as AuthenticatedTutorChegadaRouteImport } from './routes/_authenticated/tutor.chegada'
import { Route as AuthenticatedTutorCaesRouteImport } from './routes/_authenticated/tutor.caes'
import { Route as AuthenticatedTutorBoletinsRouteImport } from './routes/_authenticated/tutor.boletins'
import { Route as AuthenticatedTutorBanhoTosaRouteImport } from './routes/_authenticated/tutor.banho-tosa'
import { Route as AuthenticatedAppTutoresRouteImport } from './routes/_authenticated/app.tutores'
import { Route as AuthenticatedAppTreinamentoRouteImport } from './routes/_authenticated/app.treinamento'
import { Route as AuthenticatedAppTarefasRouteImport } from './routes/_authenticated/app.tarefas'
import { Route as AuthenticatedAppStoriesRouteImport } from './routes/_authenticated/app.stories'
import { Route as AuthenticatedAppSaudeRouteImport } from './routes/_authenticated/app.saude'
import { Route as AuthenticatedAppRelatoriosRouteImport } from './routes/_authenticated/app.relatorios'
import { Route as AuthenticatedAppProgramacaoRouteImport } from './routes/_authenticated/app.programacao'
import { Route as AuthenticatedAppOcorrenciasRouteImport } from './routes/_authenticated/app.ocorrencias'
import { Route as AuthenticatedAppInteligenciaFinanceiraRouteImport } from './routes/_authenticated/app.inteligencia-financeira'
import { Route as AuthenticatedAppHospedagemRouteImport } from './routes/_authenticated/app.hospedagem'
import { Route as AuthenticatedAppFuncionariosRouteImport } from './routes/_authenticated/app.funcionarios'
import { Route as AuthenticatedAppFinanceiroRouteImport } from './routes/_authenticated/app.financeiro'
import { Route as AuthenticatedAppDocumentosRouteImport } from './routes/_authenticated/app.documentos'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated/app.configuracoes'
import { Route as AuthenticatedAppComunicacaoRouteImport } from './routes/_authenticated/app.comunicacao'
import { Route as AuthenticatedAppChegadasRouteImport } from './routes/_authenticated/app.chegadas'
import { Route as AuthenticatedAppCalendarioRouteImport } from './routes/_authenticated/app.calendario'
import { Route as AuthenticatedAppCaesRouteImport } from './routes/_authenticated/app.caes'
import { Route as AuthenticatedAppBoletinsRouteImport } from './routes/_authenticated/app.boletins'
import { Route as AuthenticatedAppBanhoTosaRouteImport } from './routes/_authenticated/app.banho-tosa'
import { Route as AuthenticatedAppAgendaRouteImport } from './routes/_authenticated/app.agenda'
import { Route as AuthenticatedAppHospedagemIdRelatorioRouteImport } from './routes/_authenticated/app.hospedagem.$id.relatorio'
import { Route as AuthenticatedAppCaesIdTimelineRouteImport } from './routes/_authenticated/app.caes.$id.timeline'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTutorRoute = AuthenticatedTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTutorIndexRoute = AuthenticatedTutorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTutorRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedTutorStoriesRoute =
  AuthenticatedTutorStoriesRouteImport.update({
    id: '/stories',
    path: '/stories',
    getParentRoute: () => AuthenticatedTutorRoute,
  } as any)
const AuthenticatedTutorFinanceiroRoute =
  AuthenticatedTutorFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedTutorRoute,
  } as any)
const AuthenticatedTutorDocumentosRoute =
  AuthenticatedTutorDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AuthenticatedTutorRoute,
  } as any)
const AuthenticatedTutorChegadaRoute =
  AuthenticatedTutorChegadaRouteImport.update({
    id: '/chegada',
    path: '/chegada',
    getParentRoute: () => AuthenticatedTutorRoute,
  } as any)
const AuthenticatedTutorCaesRoute = AuthenticatedTutorCaesRouteImport.update({
  id: '/caes',
  path: '/caes',
  getParentRoute: () => AuthenticatedTutorRoute,
} as any)
const AuthenticatedTutorBoletinsRoute =
  AuthenticatedTutorBoletinsRouteImport.update({
    id: '/boletins',
    path: '/boletins',
    getParentRoute: () => AuthenticatedTutorRoute,
  } as any)
const AuthenticatedTutorBanhoTosaRoute =
  AuthenticatedTutorBanhoTosaRouteImport.update({
    id: '/banho-tosa',
    path: '/banho-tosa',
    getParentRoute: () => AuthenticatedTutorRoute,
  } as any)
const AuthenticatedAppTutoresRoute = AuthenticatedAppTutoresRouteImport.update({
  id: '/tutores',
  path: '/tutores',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTreinamentoRoute =
  AuthenticatedAppTreinamentoRouteImport.update({
    id: '/treinamento',
    path: '/treinamento',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTarefasRoute = AuthenticatedAppTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppStoriesRoute = AuthenticatedAppStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSaudeRoute = AuthenticatedAppSaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRelatoriosRoute =
  AuthenticatedAppRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProgramacaoRoute =
  AuthenticatedAppProgramacaoRouteImport.update({
    id: '/programacao',
    path: '/programacao',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOcorrenciasRoute =
  AuthenticatedAppOcorrenciasRouteImport.update({
    id: '/ocorrencias',
    path: '/ocorrencias',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInteligenciaFinanceiraRoute =
  AuthenticatedAppInteligenciaFinanceiraRouteImport.update({
    id: '/inteligencia-financeira',
    path: '/inteligencia-financeira',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHospedagemRoute =
  AuthenticatedAppHospedagemRouteImport.update({
    id: '/hospedagem',
    path: '/hospedagem',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFuncionariosRoute =
  AuthenticatedAppFuncionariosRouteImport.update({
    id: '/funcionarios',
    path: '/funcionarios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFinanceiroRoute =
  AuthenticatedAppFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDocumentosRoute =
  AuthenticatedAppDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppComunicacaoRoute =
  AuthenticatedAppComunicacaoRouteImport.update({
    id: '/comunicacao',
    path: '/comunicacao',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChegadasRoute =
  AuthenticatedAppChegadasRouteImport.update({
    id: '/chegadas',
    path: '/chegadas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCalendarioRoute =
  AuthenticatedAppCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCaesRoute = AuthenticatedAppCaesRouteImport.update({
  id: '/caes',
  path: '/caes',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBoletinsRoute =
  AuthenticatedAppBoletinsRouteImport.update({
    id: '/boletins',
    path: '/boletins',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBanhoTosaRoute =
  AuthenticatedAppBanhoTosaRouteImport.update({
    id: '/banho-tosa',
    path: '/banho-tosa',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAgendaRoute = AuthenticatedAppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppHospedagemIdRelatorioRoute =
  AuthenticatedAppHospedagemIdRelatorioRouteImport.update({
    id: '/$id/relatorio',
    path: '/$id/relatorio',
    getParentRoute: () => AuthenticatedAppHospedagemRoute,
  } as any)
const AuthenticatedAppCaesIdTimelineRoute =
  AuthenticatedAppCaesIdTimelineRouteImport.update({
    id: '/$id/timeline',
    path: '/$id/timeline',
    getParentRoute: () => AuthenticatedAppCaesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/tutor': typeof AuthenticatedTutorRouteWithChildren
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/banho-tosa': typeof AuthenticatedAppBanhoTosaRoute
  '/app/boletins': typeof AuthenticatedAppBoletinsRoute
  '/app/caes': typeof AuthenticatedAppCaesRouteWithChildren
  '/app/calendario': typeof AuthenticatedAppCalendarioRoute
  '/app/chegadas': typeof AuthenticatedAppChegadasRoute
  '/app/comunicacao': typeof AuthenticatedAppComunicacaoRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/app/funcionarios': typeof AuthenticatedAppFuncionariosRoute
  '/app/hospedagem': typeof AuthenticatedAppHospedagemRouteWithChildren
  '/app/inteligencia-financeira': typeof AuthenticatedAppInteligenciaFinanceiraRoute
  '/app/ocorrencias': typeof AuthenticatedAppOcorrenciasRoute
  '/app/programacao': typeof AuthenticatedAppProgramacaoRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app/saude': typeof AuthenticatedAppSaudeRoute
  '/app/stories': typeof AuthenticatedAppStoriesRoute
  '/app/tarefas': typeof AuthenticatedAppTarefasRoute
  '/app/treinamento': typeof AuthenticatedAppTreinamentoRoute
  '/app/tutores': typeof AuthenticatedAppTutoresRoute
  '/tutor/banho-tosa': typeof AuthenticatedTutorBanhoTosaRoute
  '/tutor/boletins': typeof AuthenticatedTutorBoletinsRoute
  '/tutor/caes': typeof AuthenticatedTutorCaesRoute
  '/tutor/chegada': typeof AuthenticatedTutorChegadaRoute
  '/tutor/documentos': typeof AuthenticatedTutorDocumentosRoute
  '/tutor/financeiro': typeof AuthenticatedTutorFinanceiroRoute
  '/tutor/stories': typeof AuthenticatedTutorStoriesRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/tutor/': typeof AuthenticatedTutorIndexRoute
  '/app/caes/$id/timeline': typeof AuthenticatedAppCaesIdTimelineRoute
  '/app/hospedagem/$id/relatorio': typeof AuthenticatedAppHospedagemIdRelatorioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/banho-tosa': typeof AuthenticatedAppBanhoTosaRoute
  '/app/boletins': typeof AuthenticatedAppBoletinsRoute
  '/app/caes': typeof AuthenticatedAppCaesRouteWithChildren
  '/app/calendario': typeof AuthenticatedAppCalendarioRoute
  '/app/chegadas': typeof AuthenticatedAppChegadasRoute
  '/app/comunicacao': typeof AuthenticatedAppComunicacaoRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/app/funcionarios': typeof AuthenticatedAppFuncionariosRoute
  '/app/hospedagem': typeof AuthenticatedAppHospedagemRouteWithChildren
  '/app/inteligencia-financeira': typeof AuthenticatedAppInteligenciaFinanceiraRoute
  '/app/ocorrencias': typeof AuthenticatedAppOcorrenciasRoute
  '/app/programacao': typeof AuthenticatedAppProgramacaoRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app/saude': typeof AuthenticatedAppSaudeRoute
  '/app/stories': typeof AuthenticatedAppStoriesRoute
  '/app/tarefas': typeof AuthenticatedAppTarefasRoute
  '/app/treinamento': typeof AuthenticatedAppTreinamentoRoute
  '/app/tutores': typeof AuthenticatedAppTutoresRoute
  '/tutor/banho-tosa': typeof AuthenticatedTutorBanhoTosaRoute
  '/tutor/boletins': typeof AuthenticatedTutorBoletinsRoute
  '/tutor/caes': typeof AuthenticatedTutorCaesRoute
  '/tutor/chegada': typeof AuthenticatedTutorChegadaRoute
  '/tutor/documentos': typeof AuthenticatedTutorDocumentosRoute
  '/tutor/financeiro': typeof AuthenticatedTutorFinanceiroRoute
  '/tutor/stories': typeof AuthenticatedTutorStoriesRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/tutor': typeof AuthenticatedTutorIndexRoute
  '/app/caes/$id/timeline': typeof AuthenticatedAppCaesIdTimelineRoute
  '/app/hospedagem/$id/relatorio': typeof AuthenticatedAppHospedagemIdRelatorioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/tutor': typeof AuthenticatedTutorRouteWithChildren
  '/_authenticated/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/_authenticated/app/banho-tosa': typeof AuthenticatedAppBanhoTosaRoute
  '/_authenticated/app/boletins': typeof AuthenticatedAppBoletinsRoute
  '/_authenticated/app/caes': typeof AuthenticatedAppCaesRouteWithChildren
  '/_authenticated/app/calendario': typeof AuthenticatedAppCalendarioRoute
  '/_authenticated/app/chegadas': typeof AuthenticatedAppChegadasRoute
  '/_authenticated/app/comunicacao': typeof AuthenticatedAppComunicacaoRoute
  '/_authenticated/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/_authenticated/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/_authenticated/app/funcionarios': typeof AuthenticatedAppFuncionariosRoute
  '/_authenticated/app/hospedagem': typeof AuthenticatedAppHospedagemRouteWithChildren
  '/_authenticated/app/inteligencia-financeira': typeof AuthenticatedAppInteligenciaFinanceiraRoute
  '/_authenticated/app/ocorrencias': typeof AuthenticatedAppOcorrenciasRoute
  '/_authenticated/app/programacao': typeof AuthenticatedAppProgramacaoRoute
  '/_authenticated/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/_authenticated/app/saude': typeof AuthenticatedAppSaudeRoute
  '/_authenticated/app/stories': typeof AuthenticatedAppStoriesRoute
  '/_authenticated/app/tarefas': typeof AuthenticatedAppTarefasRoute
  '/_authenticated/app/treinamento': typeof AuthenticatedAppTreinamentoRoute
  '/_authenticated/app/tutores': typeof AuthenticatedAppTutoresRoute
  '/_authenticated/tutor/banho-tosa': typeof AuthenticatedTutorBanhoTosaRoute
  '/_authenticated/tutor/boletins': typeof AuthenticatedTutorBoletinsRoute
  '/_authenticated/tutor/caes': typeof AuthenticatedTutorCaesRoute
  '/_authenticated/tutor/chegada': typeof AuthenticatedTutorChegadaRoute
  '/_authenticated/tutor/documentos': typeof AuthenticatedTutorDocumentosRoute
  '/_authenticated/tutor/financeiro': typeof AuthenticatedTutorFinanceiroRoute
  '/_authenticated/tutor/stories': typeof AuthenticatedTutorStoriesRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/tutor/': typeof AuthenticatedTutorIndexRoute
  '/_authenticated/app/caes/$id/timeline': typeof AuthenticatedAppCaesIdTimelineRoute
  '/_authenticated/app/hospedagem/$id/relatorio': typeof AuthenticatedAppHospedagemIdRelatorioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app'
    | '/tutor'
    | '/app/agenda'
    | '/app/banho-tosa'
    | '/app/boletins'
    | '/app/caes'
    | '/app/calendario'
    | '/app/chegadas'
    | '/app/comunicacao'
    | '/app/configuracoes'
    | '/app/documentos'
    | '/app/financeiro'
    | '/app/funcionarios'
    | '/app/hospedagem'
    | '/app/inteligencia-financeira'
    | '/app/ocorrencias'
    | '/app/programacao'
    | '/app/relatorios'
    | '/app/saude'
    | '/app/stories'
    | '/app/tarefas'
    | '/app/treinamento'
    | '/app/tutores'
    | '/tutor/banho-tosa'
    | '/tutor/boletins'
    | '/tutor/caes'
    | '/tutor/chegada'
    | '/tutor/documentos'
    | '/tutor/financeiro'
    | '/tutor/stories'
    | '/app/'
    | '/tutor/'
    | '/app/caes/$id/timeline'
    | '/app/hospedagem/$id/relatorio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app/agenda'
    | '/app/banho-tosa'
    | '/app/boletins'
    | '/app/caes'
    | '/app/calendario'
    | '/app/chegadas'
    | '/app/comunicacao'
    | '/app/configuracoes'
    | '/app/documentos'
    | '/app/financeiro'
    | '/app/funcionarios'
    | '/app/hospedagem'
    | '/app/inteligencia-financeira'
    | '/app/ocorrencias'
    | '/app/programacao'
    | '/app/relatorios'
    | '/app/saude'
    | '/app/stories'
    | '/app/tarefas'
    | '/app/treinamento'
    | '/app/tutores'
    | '/tutor/banho-tosa'
    | '/tutor/boletins'
    | '/tutor/caes'
    | '/tutor/chegada'
    | '/tutor/documentos'
    | '/tutor/financeiro'
    | '/tutor/stories'
    | '/app'
    | '/tutor'
    | '/app/caes/$id/timeline'
    | '/app/hospedagem/$id/relatorio'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/tutor'
    | '/_authenticated/app/agenda'
    | '/_authenticated/app/banho-tosa'
    | '/_authenticated/app/boletins'
    | '/_authenticated/app/caes'
    | '/_authenticated/app/calendario'
    | '/_authenticated/app/chegadas'
    | '/_authenticated/app/comunicacao'
    | '/_authenticated/app/configuracoes'
    | '/_authenticated/app/documentos'
    | '/_authenticated/app/financeiro'
    | '/_authenticated/app/funcionarios'
    | '/_authenticated/app/hospedagem'
    | '/_authenticated/app/inteligencia-financeira'
    | '/_authenticated/app/ocorrencias'
    | '/_authenticated/app/programacao'
    | '/_authenticated/app/relatorios'
    | '/_authenticated/app/saude'
    | '/_authenticated/app/stories'
    | '/_authenticated/app/tarefas'
    | '/_authenticated/app/treinamento'
    | '/_authenticated/app/tutores'
    | '/_authenticated/tutor/banho-tosa'
    | '/_authenticated/tutor/boletins'
    | '/_authenticated/tutor/caes'
    | '/_authenticated/tutor/chegada'
    | '/_authenticated/tutor/documentos'
    | '/_authenticated/tutor/financeiro'
    | '/_authenticated/tutor/stories'
    | '/_authenticated/app/'
    | '/_authenticated/tutor/'
    | '/_authenticated/app/caes/$id/timeline'
    | '/_authenticated/app/hospedagem/$id/relatorio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tutor': {
      id: '/_authenticated/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AuthenticatedTutorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutor/': {
      id: '/_authenticated/tutor/'
      path: '/'
      fullPath: '/tutor/'
      preLoaderRoute: typeof AuthenticatedTutorIndexRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/tutor/stories': {
      id: '/_authenticated/tutor/stories'
      path: '/stories'
      fullPath: '/tutor/stories'
      preLoaderRoute: typeof AuthenticatedTutorStoriesRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
    '/_authenticated/tutor/financeiro': {
      id: '/_authenticated/tutor/financeiro'
      path: '/financeiro'
      fullPath: '/tutor/financeiro'
      preLoaderRoute: typeof AuthenticatedTutorFinanceiroRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
    '/_authenticated/tutor/documentos': {
      id: '/_authenticated/tutor/documentos'
      path: '/documentos'
      fullPath: '/tutor/documentos'
      preLoaderRoute: typeof AuthenticatedTutorDocumentosRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
    '/_authenticated/tutor/chegada': {
      id: '/_authenticated/tutor/chegada'
      path: '/chegada'
      fullPath: '/tutor/chegada'
      preLoaderRoute: typeof AuthenticatedTutorChegadaRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
    '/_authenticated/tutor/caes': {
      id: '/_authenticated/tutor/caes'
      path: '/caes'
      fullPath: '/tutor/caes'
      preLoaderRoute: typeof AuthenticatedTutorCaesRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
    '/_authenticated/tutor/boletins': {
      id: '/_authenticated/tutor/boletins'
      path: '/boletins'
      fullPath: '/tutor/boletins'
      preLoaderRoute: typeof AuthenticatedTutorBoletinsRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
    '/_authenticated/tutor/banho-tosa': {
      id: '/_authenticated/tutor/banho-tosa'
      path: '/banho-tosa'
      fullPath: '/tutor/banho-tosa'
      preLoaderRoute: typeof AuthenticatedTutorBanhoTosaRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
    '/_authenticated/app/tutores': {
      id: '/_authenticated/app/tutores'
      path: '/tutores'
      fullPath: '/app/tutores'
      preLoaderRoute: typeof AuthenticatedAppTutoresRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/treinamento': {
      id: '/_authenticated/app/treinamento'
      path: '/treinamento'
      fullPath: '/app/treinamento'
      preLoaderRoute: typeof AuthenticatedAppTreinamentoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tarefas': {
      id: '/_authenticated/app/tarefas'
      path: '/tarefas'
      fullPath: '/app/tarefas'
      preLoaderRoute: typeof AuthenticatedAppTarefasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/stories': {
      id: '/_authenticated/app/stories'
      path: '/stories'
      fullPath: '/app/stories'
      preLoaderRoute: typeof AuthenticatedAppStoriesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/saude': {
      id: '/_authenticated/app/saude'
      path: '/saude'
      fullPath: '/app/saude'
      preLoaderRoute: typeof AuthenticatedAppSaudeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/relatorios': {
      id: '/_authenticated/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AuthenticatedAppRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/programacao': {
      id: '/_authenticated/app/programacao'
      path: '/programacao'
      fullPath: '/app/programacao'
      preLoaderRoute: typeof AuthenticatedAppProgramacaoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ocorrencias': {
      id: '/_authenticated/app/ocorrencias'
      path: '/ocorrencias'
      fullPath: '/app/ocorrencias'
      preLoaderRoute: typeof AuthenticatedAppOcorrenciasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/inteligencia-financeira': {
      id: '/_authenticated/app/inteligencia-financeira'
      path: '/inteligencia-financeira'
      fullPath: '/app/inteligencia-financeira'
      preLoaderRoute: typeof AuthenticatedAppInteligenciaFinanceiraRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/hospedagem': {
      id: '/_authenticated/app/hospedagem'
      path: '/hospedagem'
      fullPath: '/app/hospedagem'
      preLoaderRoute: typeof AuthenticatedAppHospedagemRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/funcionarios': {
      id: '/_authenticated/app/funcionarios'
      path: '/funcionarios'
      fullPath: '/app/funcionarios'
      preLoaderRoute: typeof AuthenticatedAppFuncionariosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/financeiro': {
      id: '/_authenticated/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/documentos': {
      id: '/_authenticated/app/documentos'
      path: '/documentos'
      fullPath: '/app/documentos'
      preLoaderRoute: typeof AuthenticatedAppDocumentosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/configuracoes': {
      id: '/_authenticated/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/comunicacao': {
      id: '/_authenticated/app/comunicacao'
      path: '/comunicacao'
      fullPath: '/app/comunicacao'
      preLoaderRoute: typeof AuthenticatedAppComunicacaoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chegadas': {
      id: '/_authenticated/app/chegadas'
      path: '/chegadas'
      fullPath: '/app/chegadas'
      preLoaderRoute: typeof AuthenticatedAppChegadasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/calendario': {
      id: '/_authenticated/app/calendario'
      path: '/calendario'
      fullPath: '/app/calendario'
      preLoaderRoute: typeof AuthenticatedAppCalendarioRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/caes': {
      id: '/_authenticated/app/caes'
      path: '/caes'
      fullPath: '/app/caes'
      preLoaderRoute: typeof AuthenticatedAppCaesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/boletins': {
      id: '/_authenticated/app/boletins'
      path: '/boletins'
      fullPath: '/app/boletins'
      preLoaderRoute: typeof AuthenticatedAppBoletinsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/banho-tosa': {
      id: '/_authenticated/app/banho-tosa'
      path: '/banho-tosa'
      fullPath: '/app/banho-tosa'
      preLoaderRoute: typeof AuthenticatedAppBanhoTosaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agenda': {
      id: '/_authenticated/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AuthenticatedAppAgendaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/hospedagem/$id/relatorio': {
      id: '/_authenticated/app/hospedagem/$id/relatorio'
      path: '/$id/relatorio'
      fullPath: '/app/hospedagem/$id/relatorio'
      preLoaderRoute: typeof AuthenticatedAppHospedagemIdRelatorioRouteImport
      parentRoute: typeof AuthenticatedAppHospedagemRoute
    }
    '/_authenticated/app/caes/$id/timeline': {
      id: '/_authenticated/app/caes/$id/timeline'
      path: '/$id/timeline'
      fullPath: '/app/caes/$id/timeline'
      preLoaderRoute: typeof AuthenticatedAppCaesIdTimelineRouteImport
      parentRoute: typeof AuthenticatedAppCaesRoute
    }
  }
}

interface AuthenticatedAppCaesRouteChildren {
  AuthenticatedAppCaesIdTimelineRoute: typeof AuthenticatedAppCaesIdTimelineRoute
}

const AuthenticatedAppCaesRouteChildren: AuthenticatedAppCaesRouteChildren = {
  AuthenticatedAppCaesIdTimelineRoute: AuthenticatedAppCaesIdTimelineRoute,
}

const AuthenticatedAppCaesRouteWithChildren =
  AuthenticatedAppCaesRoute._addFileChildren(AuthenticatedAppCaesRouteChildren)

interface AuthenticatedAppHospedagemRouteChildren {
  AuthenticatedAppHospedagemIdRelatorioRoute: typeof AuthenticatedAppHospedagemIdRelatorioRoute
}

const AuthenticatedAppHospedagemRouteChildren: AuthenticatedAppHospedagemRouteChildren =
  {
    AuthenticatedAppHospedagemIdRelatorioRoute:
      AuthenticatedAppHospedagemIdRelatorioRoute,
  }

const AuthenticatedAppHospedagemRouteWithChildren =
  AuthenticatedAppHospedagemRoute._addFileChildren(
    AuthenticatedAppHospedagemRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAgendaRoute: typeof AuthenticatedAppAgendaRoute
  AuthenticatedAppBanhoTosaRoute: typeof AuthenticatedAppBanhoTosaRoute
  AuthenticatedAppBoletinsRoute: typeof AuthenticatedAppBoletinsRoute
  AuthenticatedAppCaesRoute: typeof AuthenticatedAppCaesRouteWithChildren
  AuthenticatedAppCalendarioRoute: typeof AuthenticatedAppCalendarioRoute
  AuthenticatedAppChegadasRoute: typeof AuthenticatedAppChegadasRoute
  AuthenticatedAppComunicacaoRoute: typeof AuthenticatedAppComunicacaoRoute
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppDocumentosRoute: typeof AuthenticatedAppDocumentosRoute
  AuthenticatedAppFinanceiroRoute: typeof AuthenticatedAppFinanceiroRoute
  AuthenticatedAppFuncionariosRoute: typeof AuthenticatedAppFuncionariosRoute
  AuthenticatedAppHospedagemRoute: typeof AuthenticatedAppHospedagemRouteWithChildren
  AuthenticatedAppInteligenciaFinanceiraRoute: typeof AuthenticatedAppInteligenciaFinanceiraRoute
  AuthenticatedAppOcorrenciasRoute: typeof AuthenticatedAppOcorrenciasRoute
  AuthenticatedAppProgramacaoRoute: typeof AuthenticatedAppProgramacaoRoute
  AuthenticatedAppRelatoriosRoute: typeof AuthenticatedAppRelatoriosRoute
  AuthenticatedAppSaudeRoute: typeof AuthenticatedAppSaudeRoute
  AuthenticatedAppStoriesRoute: typeof AuthenticatedAppStoriesRoute
  AuthenticatedAppTarefasRoute: typeof AuthenticatedAppTarefasRoute
  AuthenticatedAppTreinamentoRoute: typeof AuthenticatedAppTreinamentoRoute
  AuthenticatedAppTutoresRoute: typeof AuthenticatedAppTutoresRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAgendaRoute: AuthenticatedAppAgendaRoute,
  AuthenticatedAppBanhoTosaRoute: AuthenticatedAppBanhoTosaRoute,
  AuthenticatedAppBoletinsRoute: AuthenticatedAppBoletinsRoute,
  AuthenticatedAppCaesRoute: AuthenticatedAppCaesRouteWithChildren,
  AuthenticatedAppCalendarioRoute: AuthenticatedAppCalendarioRoute,
  AuthenticatedAppChegadasRoute: AuthenticatedAppChegadasRoute,
  AuthenticatedAppComunicacaoRoute: AuthenticatedAppComunicacaoRoute,
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppDocumentosRoute: AuthenticatedAppDocumentosRoute,
  AuthenticatedAppFinanceiroRoute: AuthenticatedAppFinanceiroRoute,
  AuthenticatedAppFuncionariosRoute: AuthenticatedAppFuncionariosRoute,
  AuthenticatedAppHospedagemRoute: AuthenticatedAppHospedagemRouteWithChildren,
  AuthenticatedAppInteligenciaFinanceiraRoute:
    AuthenticatedAppInteligenciaFinanceiraRoute,
  AuthenticatedAppOcorrenciasRoute: AuthenticatedAppOcorrenciasRoute,
  AuthenticatedAppProgramacaoRoute: AuthenticatedAppProgramacaoRoute,
  AuthenticatedAppRelatoriosRoute: AuthenticatedAppRelatoriosRoute,
  AuthenticatedAppSaudeRoute: AuthenticatedAppSaudeRoute,
  AuthenticatedAppStoriesRoute: AuthenticatedAppStoriesRoute,
  AuthenticatedAppTarefasRoute: AuthenticatedAppTarefasRoute,
  AuthenticatedAppTreinamentoRoute: AuthenticatedAppTreinamentoRoute,
  AuthenticatedAppTutoresRoute: AuthenticatedAppTutoresRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedTutorRouteChildren {
  AuthenticatedTutorBanhoTosaRoute: typeof AuthenticatedTutorBanhoTosaRoute
  AuthenticatedTutorBoletinsRoute: typeof AuthenticatedTutorBoletinsRoute
  AuthenticatedTutorCaesRoute: typeof AuthenticatedTutorCaesRoute
  AuthenticatedTutorChegadaRoute: typeof AuthenticatedTutorChegadaRoute
  AuthenticatedTutorDocumentosRoute: typeof AuthenticatedTutorDocumentosRoute
  AuthenticatedTutorFinanceiroRoute: typeof AuthenticatedTutorFinanceiroRoute
  AuthenticatedTutorStoriesRoute: typeof AuthenticatedTutorStoriesRoute
  AuthenticatedTutorIndexRoute: typeof AuthenticatedTutorIndexRoute
}

const AuthenticatedTutorRouteChildren: AuthenticatedTutorRouteChildren = {
  AuthenticatedTutorBanhoTosaRoute: AuthenticatedTutorBanhoTosaRoute,
  AuthenticatedTutorBoletinsRoute: AuthenticatedTutorBoletinsRoute,
  AuthenticatedTutorCaesRoute: AuthenticatedTutorCaesRoute,
  AuthenticatedTutorChegadaRoute: AuthenticatedTutorChegadaRoute,
  AuthenticatedTutorDocumentosRoute: AuthenticatedTutorDocumentosRoute,
  AuthenticatedTutorFinanceiroRoute: AuthenticatedTutorFinanceiroRoute,
  AuthenticatedTutorStoriesRoute: AuthenticatedTutorStoriesRoute,
  AuthenticatedTutorIndexRoute: AuthenticatedTutorIndexRoute,
}

const AuthenticatedTutorRouteWithChildren =
  AuthenticatedTutorRoute._addFileChildren(AuthenticatedTutorRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedTutorRoute: typeof AuthenticatedTutorRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedTutorRoute: AuthenticatedTutorRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
