/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppTutoresRouteImport } from './routes/_authenticated/app.tutores'
import { Route as AuthenticatedAppSaudeRouteImport } from './routes/_authenticated/app.saude'
import { Route as AuthenticatedAppOcorrenciasRouteImport } from './routes/_authenticated/app.ocorrencias'
import { Route as AuthenticatedAppHospedagemRouteImport } from './routes/_authenticated/app.hospedagem'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated/app.configuracoes'
import { Route as AuthenticatedAppCaesRouteImport } from './routes/_authenticated/app.caes'
import { Route as AuthenticatedAppBanhoTosaRouteImport } from './routes/_authenticated/app.banho-tosa'
import { Route as AuthenticatedAppAgendaRouteImport } from './routes/_authenticated/app.agenda'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTutoresRoute = AuthenticatedAppTutoresRouteImport.update({
  id: '/tutores',
  path: '/tutores',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSaudeRoute = AuthenticatedAppSaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOcorrenciasRoute =
  AuthenticatedAppOcorrenciasRouteImport.update({
    id: '/ocorrencias',
    path: '/ocorrencias',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHospedagemRoute =
  AuthenticatedAppHospedagemRouteImport.update({
    id: '/hospedagem',
    path: '/hospedagem',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCaesRoute = AuthenticatedAppCaesRouteImport.update({
  id: '/caes',
  path: '/caes',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBanhoTosaRoute =
  AuthenticatedAppBanhoTosaRouteImport.update({
    id: '/banho-tosa',
    path: '/banho-tosa',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAgendaRoute = AuthenticatedAppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/banho-tosa': typeof AuthenticatedAppBanhoTosaRoute
  '/app/caes': typeof AuthenticatedAppCaesRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/hospedagem': typeof AuthenticatedAppHospedagemRoute
  '/app/ocorrencias': typeof AuthenticatedAppOcorrenciasRoute
  '/app/saude': typeof AuthenticatedAppSaudeRoute
  '/app/tutores': typeof AuthenticatedAppTutoresRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/banho-tosa': typeof AuthenticatedAppBanhoTosaRoute
  '/app/caes': typeof AuthenticatedAppCaesRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/hospedagem': typeof AuthenticatedAppHospedagemRoute
  '/app/ocorrencias': typeof AuthenticatedAppOcorrenciasRoute
  '/app/saude': typeof AuthenticatedAppSaudeRoute
  '/app/tutores': typeof AuthenticatedAppTutoresRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/_authenticated/app/banho-tosa': typeof AuthenticatedAppBanhoTosaRoute
  '/_authenticated/app/caes': typeof AuthenticatedAppCaesRoute
  '/_authenticated/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/app/hospedagem': typeof AuthenticatedAppHospedagemRoute
  '/_authenticated/app/ocorrencias': typeof AuthenticatedAppOcorrenciasRoute
  '/_authenticated/app/saude': typeof AuthenticatedAppSaudeRoute
  '/_authenticated/app/tutores': typeof AuthenticatedAppTutoresRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app'
    | '/app/agenda'
    | '/app/banho-tosa'
    | '/app/caes'
    | '/app/configuracoes'
    | '/app/hospedagem'
    | '/app/ocorrencias'
    | '/app/saude'
    | '/app/tutores'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app/agenda'
    | '/app/banho-tosa'
    | '/app/caes'
    | '/app/configuracoes'
    | '/app/hospedagem'
    | '/app/ocorrencias'
    | '/app/saude'
    | '/app/tutores'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/app/agenda'
    | '/_authenticated/app/banho-tosa'
    | '/_authenticated/app/caes'
    | '/_authenticated/app/configuracoes'
    | '/_authenticated/app/hospedagem'
    | '/_authenticated/app/ocorrencias'
    | '/_authenticated/app/saude'
    | '/_authenticated/app/tutores'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tutores': {
      id: '/_authenticated/app/tutores'
      path: '/tutores'
      fullPath: '/app/tutores'
      preLoaderRoute: typeof AuthenticatedAppTutoresRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/saude': {
      id: '/_authenticated/app/saude'
      path: '/saude'
      fullPath: '/app/saude'
      preLoaderRoute: typeof AuthenticatedAppSaudeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ocorrencias': {
      id: '/_authenticated/app/ocorrencias'
      path: '/ocorrencias'
      fullPath: '/app/ocorrencias'
      preLoaderRoute: typeof AuthenticatedAppOcorrenciasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/hospedagem': {
      id: '/_authenticated/app/hospedagem'
      path: '/hospedagem'
      fullPath: '/app/hospedagem'
      preLoaderRoute: typeof AuthenticatedAppHospedagemRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/configuracoes': {
      id: '/_authenticated/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/caes': {
      id: '/_authenticated/app/caes'
      path: '/caes'
      fullPath: '/app/caes'
      preLoaderRoute: typeof AuthenticatedAppCaesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/banho-tosa': {
      id: '/_authenticated/app/banho-tosa'
      path: '/banho-tosa'
      fullPath: '/app/banho-tosa'
      preLoaderRoute: typeof AuthenticatedAppBanhoTosaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agenda': {
      id: '/_authenticated/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AuthenticatedAppAgendaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAgendaRoute: typeof AuthenticatedAppAgendaRoute
  AuthenticatedAppBanhoTosaRoute: typeof AuthenticatedAppBanhoTosaRoute
  AuthenticatedAppCaesRoute: typeof AuthenticatedAppCaesRoute
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppHospedagemRoute: typeof AuthenticatedAppHospedagemRoute
  AuthenticatedAppOcorrenciasRoute: typeof AuthenticatedAppOcorrenciasRoute
  AuthenticatedAppSaudeRoute: typeof AuthenticatedAppSaudeRoute
  AuthenticatedAppTutoresRoute: typeof AuthenticatedAppTutoresRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAgendaRoute: AuthenticatedAppAgendaRoute,
  AuthenticatedAppBanhoTosaRoute: AuthenticatedAppBanhoTosaRoute,
  AuthenticatedAppCaesRoute: AuthenticatedAppCaesRoute,
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppHospedagemRoute: AuthenticatedAppHospedagemRoute,
  AuthenticatedAppOcorrenciasRoute: AuthenticatedAppOcorrenciasRoute,
  AuthenticatedAppSaudeRoute: AuthenticatedAppSaudeRoute,
  AuthenticatedAppTutoresRoute: AuthenticatedAppTutoresRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
